export const TYPE_LABELS = {
  adsb: 'ADS-B 航空',
  ais: 'AIS 船舶',
  satellite: '卫星下行',
  cellular: '蜂窝基站',
  acars: 'ACARS 航空报文',
  aprs: 'APRS 业余无线电',
  cw: 'CW 摩尔斯',
  wifi: 'WiFi (802.11)',
  bluetooth: '蓝牙 BLE',
  paging: '寻呼 POCSAG/FLEX',
  broadcast: 'FM 广播 RDS',
  lora: 'LoRa',
  dmr: 'DMR / P25',
  tetra: 'TETRA',
  ism: 'ISM 遥控/传感器',
};

// Fields an RTL-SDR / wideband receiver can passively decode or demod.
export const MOCK_SIGNALS = [
  // ── LTE / NR / GSM ──
  {
    id: 'c1', type: 'cellular',
    label: '中国移动 B39 TDD',
    freq: '1880.0 MHz', strength: -87, strengthKey: 'rsrp',
    cols: { rat: 'LTE', band: 'B39', pci: 142, earfcn: 38400, bw: '20M' },
    details: [
      ['MCC / MNC', '460 / 00'], ['TAC', '0x5E20'], ['Cell ID', '0x01A2B03'],
      ['RSRP / RSRQ', '-87 / -11 dB'], ['SINR', '8.2 dB'], ['CFO', '-312 Hz'],
      ['带宽', '20 MHz'], ['双工', 'TDD'], ['MIB', '已解'], ['PSS 相关', '0.94'],
      ['采样率', '1.92 Msps'], ['天线', 'RX1'],
    ],
    rsrp: -87,
  },
  {
    id: 'c2', type: 'cellular',
    label: '中国联通 n78 NR',
    freq: '3500.0 MHz', strength: -92, strengthKey: 'rsrp',
    cols: { rat: 'NR', band: 'n78', pci: 58, earfcn: 627264, bw: '100M' },
    details: [
      ['MCC / MNC', '460 / 01'], ['TAC', '0x3F10'], ['NCI', '0x0021A8001'],
      ['SSB Index', '2'], ['SCS', '30 kHz'], ['RSRP / SINR', '-92 / 5.1 dB'],
      ['CFO', '+148 Hz'], ['带宽', '100 MHz'], ['SSB', '已锁定'],
      ['波束', '#2'], ['采样率', '3.2 Msps'],
    ],
    rsrp: -92,
  },
  {
    id: 'c3', type: 'cellular',
    label: '中国电信 B3 FDD',
    freq: '1842.5 MHz', strength: -95, strengthKey: 'rsrp',
    cols: { rat: 'LTE', band: 'B3', pci: 301, earfcn: 1850, bw: '15M' },
    details: [
      ['MCC / MNC', '460 / 11'], ['TAC', '0x8821'], ['Cell ID', '0x00F1204'],
      ['RSRP / RSRQ', '-95 / -14 dB'], ['SINR', '3.8 dB'], ['CFO', '-89 Hz'],
      ['带宽', '15 MHz'], ['双工', 'FDD'], ['PHICH', 'Normal'],
      ['SIB1', '已解'], ['PLMN', '460-11'],
    ],
    rsrp: -95,
  },
  {
    id: 'c4', type: 'cellular',
    label: '中国移动 B41 TDD',
    freq: '2595.0 MHz', strength: -78, strengthKey: 'rsrp',
    cols: { rat: 'LTE', band: 'B41', pci: 87, earfcn: 40936, bw: '20M' },
    details: [
      ['MCC / MNC', '460 / 00'], ['TAC', '0x5E20'], ['Cell ID', '0x02C8810'],
      ['RSRP / RSRQ', '-78 / -8 dB'], ['SINR', '14.5 dB'], ['CFO', '+45 Hz'],
      ['带宽', '20 MHz'], ['双工', 'TDD'], ['TM', 'TM3'],
      ['载波聚合', 'PCC'], ['采样率', '2.048 Msps'],
    ],
    rsrp: -78,
  },
  {
    id: 'c5', type: 'cellular',
    label: 'GSM900 宏站',
    freq: '936.4 MHz', strength: -71, strengthKey: 'rssi',
    cols: { rat: 'GSM', band: 'GSM900', pci: 'BSIC 63', earfcn: 'ARFCN 62', bw: '200k' },
    details: [
      ['MCC / MNC', '460 / 00'], ['LAC', '0x12A4'], ['CI', '0x4F21'],
      ['BCCH', 'ARFCN 62'], ['BSIC', '63'], ['RSSI', '-71 dBm'],
      ['C/I', '18 dB'], ['时隙', 'TS0 (BCCH)'], ['调制', 'GMSK'],
      ['LAI', '460-00-4772'], ['协议', 'GSM Phase 2+'],
    ],
    rssi: -71,
  },

  // ── WiFi 802.11 Beacon / Probe ──
  {
    id: 'w1', type: 'wifi',
    label: 'CMCC-5G',
    freq: '5180 MHz', strength: -52, strengthKey: 'rssi',
    cols: { ssid: 'CMCC-5G', bssid: '58:D9:D5:12:A4:00', ch: '36', sec: 'WPA2' },
    details: [
      ['厂商 (OUI)', 'Tenda Technology'], ['信道 / 宽度', '36 / 80 MHz'],
      ['RSSI / SNR', '-52 / 28 dB dBm'], ['帧类型', 'Beacon'], ['Beacon 间隔', '102 ms'],
      ['最高速率', '866 Mbps (VHT)'], ['加密', 'WPA2-PSK / CCMP'],
      ['IE', 'RSN, HT Cap, VHT Cap, WMM, ERP'],
      ['包计数 (10s)', '1842'], ['中心频率', '5210 MHz'],
    ],
    rssi: -52,
  },
  {
    id: 'w2', type: 'wifi',
    label: 'Home_2.4G',
    freq: '2437 MHz', strength: -61, strengthKey: 'rssi',
    cols: { ssid: 'Home_2.4G', bssid: 'AC:85:3D:8F:01:22', ch: '6', sec: 'WPA3' },
    details: [
      ['厂商 (OUI)', 'Huawei Device'], ['信道 / 宽度', '6 / 40 MHz'],
      ['RSSI / SNR', '-61 / 22 dB'], ['帧类型', 'Beacon'],
      ['Beacon 间隔', '100 ms'], ['最高速率', '300 Mbps (HT)'],
      ['加密', 'WPA3-SAE / GCMP'], ['BSSID', 'AC:85:3D:8F:01:22'],
      ['包计数 (10s)', '956'],
    ],
    rssi: -61,
  },
  {
    id: 'w3', type: 'wifi',
    label: '(hidden)',
    freq: '2462 MHz', strength: -74, strengthKey: 'rssi',
    cols: { ssid: '(hidden)', bssid: 'F0:9F:C2:3C:88:10', ch: '11', sec: 'WPA2' },
    details: [
      ['厂商 (OUI)', 'Xiaomi Communications'], ['信道 / 宽度', '11 / 20 MHz'],
      ['RSSI / SNR', '-74 / 14 dB'], ['帧类型', 'Beacon (隐藏 SSID)'],
      ['Beacon 间隔', '100 ms'], ['加密', 'WPA2-PSK / CCMP'],
      ['Probe 响应', '是'], ['包计数 (10s)', '412'],
    ],
    rssi: -74,
  },
  {
    id: 'w4', type: 'wifi',
    label: 'Starbucks_Free',
    freq: '2412 MHz', strength: -68, strengthKey: 'rssi',
    cols: { ssid: 'Starbucks_Free', bssid: '00:1A:2B:44:20:01', ch: '1', sec: 'Open' },
    details: [
      ['厂商 (OUI)', 'Cisco Systems'], ['信道 / 宽度', '1 / 20 MHz'],
      ['RSSI / SNR', '-68 / 18 dB'], ['帧类型', 'Beacon'],
      ['加密', 'Open'], ['Captive Portal', '检测到'],
      ['Beacon 间隔', '100 ms'], ['包计数 (10s)', '623'],
    ],
    rssi: -68,
  },
  {
    id: 'w5', type: 'wifi',
    label: 'eduroam',
    freq: '5745 MHz', strength: -79, strengthKey: 'rssi',
    cols: { ssid: 'eduroam', bssid: '00:25:90:C1:02:AA', ch: '149', sec: 'WPA2-EAP' },
    details: [
      ['厂商 (OUI)', 'Ruckus Wireless'], ['信道 / 宽度', '149 / 80 MHz'],
      ['RSSI / SNR', '-79 / 11 dB'], ['帧类型', 'Beacon'],
      ['加密', 'WPA2-Enterprise / 802.1X'], ['IE', 'RSN, HT, VHT, WMM'],
      ['Beacon 间隔', '100 ms'], ['DFS', '否'],
    ],
    rssi: -79,
  },
  {
    id: 'w6', type: 'wifi',
    label: 'IoT_Sensor_GW',
    freq: '2472 MHz', strength: -83, strengthKey: 'rssi',
    cols: { ssid: 'IoT_Sensor_GW', bssid: 'B8:27:EB:A1:02:FF', ch: '13', sec: 'WPA2' },
    details: [
      ['厂商 (OUI)', 'Raspberry Pi Foundation'], ['信道 / 宽度', '13 / 20 MHz'],
      ['RSSI / SNR', '-83 / 8 dB'], ['帧类型', 'Beacon'],
      ['加密', 'WPA2-PSK'], ['802.11 标准', '802.11n'],
      ['Beacon 间隔', '200 ms'],
    ],
    rssi: -83,
  },

  // ── Bluetooth LE Advertisement ──
  {
    id: 'b1', type: 'bluetooth',
    label: 'AirPods Pro',
    freq: '2402 MHz', strength: -58, strengthKey: 'rssi',
    cols: { name: 'AirPods Pro', mac: 'A4:C1:38:9B:2E:01', kind: 'Audio', adv: 'ADV_IND' },
    details: [
      ['厂商', 'Apple Inc.'], ['Company ID', '0x004C'],
      ['MAC', 'A4:C1:38:9B:2E:01'], ['RSSI / TxPower', '-58 / -12 dBm'],
      ['广播类型', 'ADV_IND'], ['可连接', '是'], ['PHY', 'LE 1M'],
      ['广播信道', '37'], ['间隔', '1285 ms'],
      ['Service UUID', 'FE95, 180F (Battery)'],
      ['Payload', '02011A0CFF4C0010073A1F4...'],
    ],
    rssi: -58,
  },
  {
    id: 'b2', type: 'bluetooth',
    label: 'Mi Band 8',
    freq: '2426 MHz', strength: -71, strengthKey: 'rssi',
    cols: { name: 'Mi Band 8', mac: 'C8:47:8C:11:07:9A', kind: 'Wearable', adv: 'ADV_NONCONN' },
    details: [
      ['厂商', 'Xiaomi'], ['Company ID', '0x038F'],
      ['MAC', 'C8:47:8C:11:07:9A'], ['RSSI / TxPower', '-71 / -16 dBm'],
      ['广播类型', 'ADV_NONCONN_IND'], ['可连接', '否'], ['PHY', 'LE 1M'],
      ['广播信道', '38'], ['间隔', '820 ms'],
      ['Service UUID', 'FEE0 (Mi Fitness)'],
      ['Payload', '0319033801...'],
    ],
    rssi: -71,
  },
  {
    id: 'b3', type: 'bluetooth',
    label: 'Unknown LE',
    freq: '2480 MHz', strength: -82, strengthKey: 'rssi',
    cols: { name: '(unknown)', mac: 'E4:E1:26:55:AA:03', kind: 'LE', adv: 'ADV_SCAN' },
    details: [
      ['MAC', 'E4:E1:26:55:AA:03'], ['RSSI', '-82 dBm'],
      ['广播类型', 'ADV_SCAN_IND'], ['可连接', '否'], ['PHY', 'LE 1M'],
      ['广播信道', '39'], ['Manufacturer Data', '无'],
      ['Payload', '020106...'],
    ],
    rssi: -82,
  },
  {
    id: 'b4', type: 'bluetooth',
    label: 'Tesla Model 3',
    freq: '2402 MHz', strength: -65, strengthKey: 'rssi',
    cols: { name: 'Tesla Model 3', mac: 'DC:8D:8A:02:F1:00', kind: 'Auto', adv: 'ADV_IND' },
    details: [
      ['厂商', 'Tesla Inc.'], ['Company ID', '0x0215'],
      ['MAC', 'DC:8D:8A:02:F1:00'], ['RSSI / TxPower', '-65 / -8 dBm'],
      ['广播类型', 'ADV_IND'], ['可连接', '是'], ['PHY', 'LE 1M / LE Coded'],
      ['广播信道', '37'], ['Service UUID', 'FD74 (Tesla)'],
      ['Payload', '021AFD7402...'],
    ],
    rssi: -65,
  },
  {
    id: 'b5', type: 'bluetooth',
    label: 'Tile Tracker',
    freq: '2426 MHz', strength: -76, strengthKey: 'rssi',
    cols: { name: 'Tile', mac: 'F0:18:98:02:BB:11', kind: 'Tracker', adv: 'ADV_NONCONN' },
    details: [
      ['厂商', 'Tile Inc.'], ['Company ID', '0x0130'],
      ['MAC', 'F0:18:98:02:BB:11'], ['RSSI', '-76 dBm'],
      ['广播类型', 'ADV_NONCONN_IND'], ['PHY', 'LE 1M'],
      ['广播信道', '38'], ['间隔', '2000 ms'],
      ['Payload', 'FF0130...'],
    ],
    rssi: -76,
  },
  {
    id: 'b6', type: 'bluetooth',
    label: 'BLE Beacon',
    freq: '2480 MHz', strength: -69, strengthKey: 'rssi',
    cols: { name: 'iBeacon', mac: '00:11:22:33:44:55', kind: 'Beacon', adv: 'ADV_NONCONN' },
    details: [
      ['MAC', '00:11:22:33:44:55'], ['RSSI / TxPower', '-69 / -59 dBm'],
      ['广播类型', 'ADV_NONCONN_IND'], ['格式', 'Apple iBeacon'],
      ['UUID', 'E2C56DB5-DFFB-48D2-B060-D0F5A71096E0'],
      ['Major / Minor', '1 / 100'], ['PHY', 'LE 1M'],
      ['广播信道', '39'],
    ],
    rssi: -69,
  },

  // ── POCSAG Pager ──
  {
    id: 'p1', type: 'paging',
    label: 'POCSAG FLEX 同频',
    freq: '152.025 MHz', strength: -88, strengthKey: 'rssi',
    cols: { proto: 'POCSAG', baud: '512', capcode: '0123456', func: 'ALN' },
    details: [
      ['频率', '152.025 MHz'], ['调制', 'FSK ±4.5 kHz'],
      ['波特率', '512 bps'], ['Capcode', '0123456'], ['功能位', 'ALN (字母)'],
      ['RIC', '0123456'], ['RSSI', '-88 dBm'],
      ['解码', '成功'], ['内容摘要', 'CALL 001 ROOM 302...'],
      ['采样率', '250 ksps'],
    ],
    rssi: -88,
  },
  {
    id: 'p2', type: 'paging',
    label: 'POCSAG 1200',
    freq: '148.175 MHz', strength: -91, strengthKey: 'rssi',
    cols: { proto: 'POCSAG', baud: '1200', capcode: '789012', func: 'NUM' },
    details: [
      ['频率', '148.175 MHz'], ['调制', 'FSK ±4.5 kHz'],
      ['波特率', '1200 bps'], ['Capcode', '789012'], ['功能位', 'NUM (数字)'],
      ['RSSI', '-91 dBm'], ['解码', '成功'],
      ['内容摘要', '13800138000...'],
    ],
    rssi: -91,
  },
  {
    id: 'p3', type: 'paging',
    label: 'FLEX 寻呼',
    freq: '152.100 MHz', strength: -86, strengthKey: 'rssi',
    cols: { proto: 'FLEX', baud: '1600', capcode: '2048-12', func: 'ALN' },
    details: [
      ['频率', '152.100 MHz'], ['调制', 'FSK 4-level'],
      ['波特率', '1600 bps'], ['Frame', 'Phase B'], ['地址', '2048-12'],
      ['功能', 'ALN'], ['RSSI', '-86 dBm'], ['解码', '成功'],
      ['内容摘要', 'MEETING RM 501 14:00...'],
    ],
    rssi: -86,
  },

  // ── ACARS 131–136 MHz ──
  {
    id: 'ac1', type: 'acars',
    label: 'MU5101 ACARS',
    freq: '131.550 MHz', strength: -76, strengthKey: 'rssi',
    cols: { flight: 'MU5101', reg: 'B-20A6', mode: 'VHF', label: 'H1' },
    details: [
      ['频率', '131.550 MHz'], ['航班', 'MU5101'], ['注册号', 'B-20A6'],
      ['报文标签', 'H1 (DIS)'], ['调制', 'AM-MSK 2400 bps'],
      ['内容摘要', 'DISPATCH ACK / ETA 0842Z'],
      ['RSSI', '-76 dBm'], ['解码', '成功'],
    ],
    rssi: -76,
  },
  {
    id: 'ac2', type: 'acars',
    label: 'CA981 ACARS',
    freq: '131.725 MHz', strength: -81, strengthKey: 'rssi',
    cols: { flight: 'CA981', reg: 'B-1088', mode: 'VHF', label: 'Q0' },
    details: [
      ['频率', '131.725 MHz'], ['航班', 'CA981'], ['注册号', 'B-1088'],
      ['报文标签', 'Q0 (MET)'], ['调制', 'AM-MSK'],
      ['内容摘要', 'METAR ZSPD 28008KT 9999...'],
      ['RSSI', '-81 dBm'],
    ],
    rssi: -81,
  },
  {
    id: 'ac3', type: 'acars',
    label: 'CX888 ACARS',
    freq: '136.975 MHz', strength: -88, strengthKey: 'rssi',
    cols: { flight: 'CX888', reg: 'B-KQK', mode: 'SAT', label: 'M1' },
    details: [
      ['频率', '136.975 MHz'], ['航班', 'CX888'], ['注册号', 'B-KQK'],
      ['报文标签', 'M1 (POS)'], ['内容摘要', 'POS REPORT / POSN 31N122E'],
      ['RSSI', '-88 dBm'], ['备注', 'HF/VHF 同内容不同链路'],
    ],
    rssi: -88,
  },

  // ── APRS 144.8 MHz ──
  {
    id: 'ap1', type: 'aprs',
    label: 'BG6XXX-9',
    freq: '144.800 MHz', strength: -72, strengthKey: 'rssi',
    cols: { call: 'BG6XXX-9', fmt: 'APRS', path: 'WIDE1-1', type: '移动台' },
    details: [
      ['频率', '144.800 MHz'], ['呼号', 'BG6XXX-9'], ['格式', 'APRS 1200 AFSK'],
      ['位置', '31.230°N 121.470°E'], ['注释', 'Icom IC-705 / 20W'],
      ['路径', 'BG6XXX-9>WIDE1-1'], ['符号', '/[ 轿车'],
      ['RSSI', '-72 dBm'], ['解码', '成功'],
    ],
    rssi: -72,
  },
  {
    id: 'ap2', type: 'aprs',
    label: 'BH1YYY-1',
    freq: '144.800 MHz', strength: -79, strengthKey: 'rssi',
    cols: { call: 'BH1YYY-1', fmt: 'APRS', path: 'direct', type: '气象站' },
    details: [
      ['频率', '144.800 MHz'], ['呼号', 'BH1YYY-1'], ['格式', 'APRS 气象'],
      ['位置', '31.18°N 121.55°E'], ['温度', '18°C'], ['风速', '12 km/h'],
      ['路径', 'direct'], ['RSSI', '-79 dBm'],
    ],
    rssi: -79,
  },
  {
    id: 'ap3', type: 'aprs',
    label: 'SR0ISS',
    freq: '145.825 MHz', strength: -94, strengthKey: 'rssi',
    cols: { call: 'SR0ISS', fmt: 'APRS', path: 'ARISS', type: '卫星' },
    details: [
      ['频率', '145.825 MHz'], ['呼号', 'SR0ISS'], ['来源', 'ISS 业余电台'],
      ['格式', 'APRS via ARISS'], ['仰角', '12°'], ['多普勒', '+2.1 kHz'],
      ['RSSI', '-94 dBm'], ['备注', '过境窗口约 8 分钟'],
    ],
    rssi: -94,
  },

  // ── FM RDS ──
  {
    id: 'r1', type: 'broadcast',
    label: 'FM 99.7 MHz',
    freq: '99.7 MHz', strength: -42, strengthKey: 'rssi',
    cols: { pi: '0xC201', ps: 'HIT FM', pty: 'Pop Music', af: '99.7' },
    details: [
      ['频率', '99.7 MHz'], ['PI Code', '0xC201'], ['PS 台名', 'HIT FM'],
      ['PTY', 'Pop Music (10)'], ['RT 电台文本', 'Now Playing: ...'],
      ['AF 备选频率', '99.7, 103.9 MHz'], ['RSSI', '-42 dBm'],
      ['RDS 偏移', '+57 kHz'], ['解码 BER', '< 0.01%'],
      ['立体声', '是'], ['预加重', '50 μs'],
    ],
    rssi: -42,
  },
  {
    id: 'r2', type: 'broadcast',
    label: 'FM 91.5 MHz',
    freq: '91.5 MHz', strength: -55, strengthKey: 'rssi',
    cols: { pi: '0x8820', ps: 'CNR-1', pty: 'News', af: '91.5' },
    details: [
      ['频率', '91.5 MHz'], ['PI Code', '0x8820'], ['PS 台名', 'CNR-1'],
      ['PTY', 'News (1)'], ['RT 电台文本', '新闻联播 ...'],
      ['RSSI', '-55 dBm'], ['RDS 偏移', '+57 kHz'],
      ['TA / TP', '否 / 否'], ['MS', 'Music/Speech 混合'],
    ],
    rssi: -55,
  },

  // ── LoRa ──
  {
    id: 'l1', type: 'lora',
    label: 'LoRa 433 MHz',
    freq: '433.92 MHz', strength: -73, strengthKey: 'rssi',
    cols: { sf: 'SF7', bw: '125 kHz', cr: '4/5', sync: '0x34' },
    details: [
      ['频率', '433.92 MHz'], ['Spreading Factor', 'SF7'],
      ['带宽', '125 kHz'], ['Coding Rate', '4/5'], ['Sync Word', '0x34 (私有)'],
      ['RSSI / SNR', '-73 / 9.5 dB'], ['前导码', '8 sym'],
      ['载荷 (Hex)', '40A102FF8C...'], ['CRC', '通过'],
      ['调制', 'LoRa CSS'], ['DevAddr', '0x01A2B3C4'],
    ],
    rssi: -73,
  },
  {
    id: 'l2', type: 'lora',
    label: 'LoRa 868 MHz',
    freq: '868.1 MHz', strength: -81, strengthKey: 'rssi',
    cols: { sf: 'SF10', bw: '125 kHz', cr: '4/8', sync: '0x12' },
    details: [
      ['频率', '868.1 MHz'], ['Spreading Factor', 'SF10'],
      ['带宽', '125 kHz'], ['Coding Rate', '4/8'], ['Sync Word', '0x12 (LoRaWAN)'],
      ['RSSI / SNR', '-81 / 4.2 dB'], ['前导码', '12 sym'],
      ['载荷 (Hex)', '6000000001...'], ['CRC', '通过'],
      ['调制', 'LoRa CSS'], ['DevAddr', '0x260B1A2B'],
    ],
    rssi: -81,
  },

  // ── DMR / P25 数字对讲 ──
  {
    id: 'd1', type: 'dmr',
    label: 'DMR 中继 409',
    freq: '409.750 MHz', strength: -68, strengthKey: 'rssi',
    cols: { mode: 'DMR', cc: 'CC1', tg: 'TG 9', slot: 'TS1' },
    details: [
      ['频率', '409.750 MHz'], ['制式', 'DMR Tier II'], ['色码', 'CC1'],
      ['时隙', 'TS1'], ['组呼', 'TG 9 (本地)'], ['调制', '4FSK'],
      ['RSSI', '-68 dBm'], ['活动', '语音突发检测'],
      ['备注', '内容加密，仅可识别活跃时隙'],
    ],
    rssi: -68,
  },
  {
    id: 'd2', type: 'dmr',
    label: 'P25 Phase 1',
    freq: '453.125 MHz', strength: -74, strengthKey: 'rssi',
    cols: { mode: 'P25', cc: 'NAC 293', tg: 'TG 1001', slot: '—' },
    details: [
      ['频率', '453.125 MHz'], ['制式', 'P25 Phase 1'], ['NAC', '293'],
      ['组呼', 'TG 1001'], ['调制', 'C4FM'], ['RSSI', '-74 dBm'],
      ['活动', '控制信道'], ['备注', 'Trunking 系统'],
    ],
    rssi: -74,
  },
  {
    id: 'd3', type: 'dmr',
    label: 'DMR 工地',
    freq: '400.125 MHz', strength: -82, strengthKey: 'rssi',
    cols: { mode: 'DMR', cc: 'CC3', tg: 'TG 2', slot: 'TS2' },
    details: [
      ['频率', '400.125 MHz'], ['色码', 'CC3'], ['时隙', 'TS2'],
      ['组呼', 'TG 2'], ['RSSI', '-82 dBm'], ['活动', '空闲监听'],
    ],
    rssi: -82,
  },

  // ── TETRA 380–400 MHz ──
  {
    id: 't1', type: 'tetra',
    label: 'TETRA 基站 A',
    freq: '380.200 MHz', strength: -77, strengthKey: 'rssi',
    cols: { mcc: '460', mnc: '00', la: 'LA 1024', carrier: 'C1' },
    details: [
      ['频率', '380.200 MHz'], ['制式', 'TETRA'], ['MCC/MNC', '460 / 00'],
      ['位置区', 'LA 1024'], ['载波', 'C1'], ['调制', 'π/4-DQPSK'],
      ['RSSI', '-77 dBm'], ['活动', '控制信道'],
      ['备注', '应急/政务专网，语音加密'],
    ],
    rssi: -77,
  },
  {
    id: 't2', type: 'tetra',
    label: 'TETRA 基站 B',
    freq: '390.625 MHz', strength: -84, strengthKey: 'rssi',
    cols: { mcc: '460', mnc: '01', la: 'LA 2048', carrier: 'C2' },
    details: [
      ['频率', '390.625 MHz'], ['MCC/MNC', '460 / 01'], ['位置区', 'LA 2048'],
      ['载波', 'C2'], ['RSSI', '-84 dBm'], ['活动', 'SDS 数据突发'],
    ],
    rssi: -84,
  },

  // ── ISM 433 / 315 MHz ──
  {
    id: 'i1', type: 'ism',
    label: '车库门遥控',
    freq: '433.92 MHz', strength: -58, strengthKey: 'rssi',
    cols: { band: '433 MHz', mod: 'OOK', proto: '固定码', rate: '~1 kbps' },
    details: [
      ['频率', '433.920 MHz'], ['调制', 'OOK ASK'], ['协议', '固定码遥控'],
      ['脉宽', '~350 μs'], ['重复', '4 次突发'], ['RSSI', '-58 dBm'],
      ['载荷', '24 bit 固定帧'], ['备注', '常见门磁/卷帘门'],
    ],
    rssi: -58,
  },
  {
    id: 'i2', type: 'ism',
    label: 'TPMS 胎压',
    freq: '433.92 MHz', strength: -71, strengthKey: 'rssi',
    cols: { band: '433 MHz', mod: 'FSK', proto: 'TPMS', rate: '9.6 kbps' },
    details: [
      ['频率', '433.920 MHz'], ['调制', 'FSK'], ['类型', '胎压传感器 TPMS'],
      ['传感器 ID', '0xA3F21C'], ['压力', '2.4 bar'], ['温度', '28°C'],
      ['RSSI', '-71 dBm'], ['间隔', '~60 s'],
    ],
    rssi: -71,
  },
  {
    id: 'i3', type: 'ism',
    label: '汽车钥匙 315',
    freq: '315.0 MHz', strength: -65, strengthKey: 'rssi',
    cols: { band: '315 MHz', mod: 'OOK', proto: 'RKE', rate: '~2 kbps' },
    details: [
      ['频率', '315.000 MHz'], ['调制', 'OOK'], ['类型', '遥控钥匙 RKE'],
      ['厂商', '滚动码 (Keeloq 类)'], ['RSSI', '-65 dBm'],
      ['备注', '仅能检测突发，无法还原密钥'],
    ],
    rssi: -65,
  },
  {
    id: 'i4', type: 'ism',
    label: '无线温湿度',
    freq: '868.3 MHz', strength: -79, strengthKey: 'rssi',
    cols: { band: '868 MHz', mod: 'FSK', proto: '私有', rate: '1.2 kbps' },
    details: [
      ['频率', '868.300 MHz'], ['调制', 'FSK'], ['类型', '环境传感器'],
      ['温度', '22.5°C'], ['湿度', '58%'], ['设备 ID', '0x8C4A01'],
      ['RSSI', '-79 dBm'], ['间隔', '30 s'],
    ],
    rssi: -79,
  },
];

export const GROUP_ORDER = [
  'adsb', 'ais', 'satellite', 'cellular', 'acars', 'aprs', 'cw',
  'wifi', 'bluetooth', 'paging', 'broadcast', 'lora',
  'dmr', 'tetra', 'ism',
];

// Column headers per signal type for summary table.
export const TABLE_COLS = {
  adsb: [
    { key: 'icao', label: 'ICAO' },
    { key: 'callsign', label: '呼号' },
    { key: 'alt', label: '高度' },
    { key: 'speed', label: '地速' },
  ],
  ais: [
    { key: 'mmsi', label: 'MMSI' },
    { key: 'sog', label: '航速' },
    { key: 'cog', label: '航向' },
    { key: 'ch', label: '信道' },
  ],
  satellite: [
    { key: 'svc', label: '业务' },
    { key: 'mod', label: '调制' },
    { key: 'sub', label: '2400Hz' },
    { key: 'dir', label: '方向' },
  ],
  cellular: [
    { key: 'rat', label: '制式' },
    { key: 'band', label: '频段' },
    { key: 'pci', label: 'PCI/BSIC' },
    { key: 'earfcn', label: 'ARFCN' },
    { key: 'bw', label: '带宽' },
  ],
  acars: [
    { key: 'flight', label: '航班' },
    { key: 'reg', label: '注册号' },
    { key: 'mode', label: '链路' },
    { key: 'label', label: '标签' },
  ],
  aprs: [
    { key: 'call', label: '呼号' },
    { key: 'fmt', label: '格式' },
    { key: 'path', label: '路径' },
    { key: 'type', label: '类型' },
  ],
  cw: [
    { key: 'mod', label: '调制' },
    { key: 'bw', label: '带宽' },
    { key: 'band', label: '波段' },
    { key: 'note', label: '备注' },
  ],
  wifi: [
    { key: 'ssid', label: 'SSID' },
    { key: 'bssid', label: 'BSSID' },
    { key: 'ch', label: '信道' },
    { key: 'sec', label: '加密' },
  ],
  bluetooth: [
    { key: 'name', label: '名称' },
    { key: 'mac', label: 'MAC' },
    { key: 'kind', label: '类型' },
    { key: 'adv', label: '广播' },
  ],
  paging: [
    { key: 'proto', label: '协议' },
    { key: 'baud', label: '波特率' },
    { key: 'capcode', label: 'Capcode' },
    { key: 'func', label: '功能' },
  ],
  broadcast: [
    { key: 'pi', label: 'PI' },
    { key: 'ps', label: '台名' },
    { key: 'pty', label: 'PTY' },
    { key: 'af', label: 'AF' },
  ],
  lora: [
    { key: 'sf', label: 'SF' },
    { key: 'bw', label: '带宽' },
    { key: 'cr', label: 'CR' },
    { key: 'sync', label: 'Sync' },
  ],
  dmr: [
    { key: 'mode', label: '制式' },
    { key: 'cc', label: '色码/NAC' },
    { key: 'tg', label: '组呼' },
    { key: 'slot', label: '时隙' },
  ],
  tetra: [
    { key: 'mcc', label: 'MCC' },
    { key: 'mnc', label: 'MNC' },
    { key: 'la', label: '位置区' },
    { key: 'carrier', label: '载波' },
  ],
  ism: [
    { key: 'band', label: '频段' },
    { key: 'mod', label: '调制' },
    { key: 'proto', label: '协议' },
    { key: 'rate', label: '速率' },
  ],
};
